<a href="https://colab.research.google.com/github/hamiin47/Assignment/blob/main/9_6_%EC%84%B8%EC%85%98_%EB%AC%B8%EC%A0%9C_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [1]:
import numpy as np

A = np.random.random((5,3))
B = np.random.random((3,2))

np.dot(A,B)

array([[0.2382624 , 0.30367935],
       [0.84780191, 0.72034898],
       [0.79979645, 0.54352448],
       [1.39671283, 1.03270475],
       [1.15455543, 0.73616396]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [4]:
import numpy as np

A=np.arange(10)
print(A)
A[(3<A)&(A<8)] = A[(3<A)&(A<8)]*-1
print(A)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9
10

- 0,1,2,3,4를 합한 값에 -1을 더함
- -1이 축 역할을 하나 축을 가지지 않기 때문에 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- legal : Z**Z, 2 << Z >> 2,1j*Z, Z/1/1
- illegal : Z <- Z, Z < Z > Z
- <- 는 파이썬의 대입 연산자가 아님

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

<ipython-input-30-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)

<ipython-input-31-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

<ipython-input-32-ea171f4782f5>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

1. 0으로 나누는 것은 정의되지 않기 때문에 nan
2. 0으로 나누는 것은 정의되지 않기 때문에 nan
3. nan의 형태를 변환할 수 없으므로 오류

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [7]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(Z1, Z2)
print("Z1:", Z1)
print("Z2:", Z2)
print("common_values:", common_values)

Z1: [4 5 1 2 2 6 0 1 7 2]
Z2: [1 9 4 3 5 4 1 7 5 5]
common_values: [1 4 5 7]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [8]:
np.sqrt(-1) == np.emath.sqrt(-1)
np.sqrt(-1)
np.emath.sqrt(-1)

<ipython-input-8-deadca2c2cb6>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-8-deadca2c2cb6>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


1j

False np.sqrt(-1)는 nan을 반환, np.emath.sqrt(-1)는 복소수 1j를 반환

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [9]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [10]:
import numpy as np

A = np.array([1, 2, 3, 4], dtype=float)
B = np.array([5, 6, 7, 8])

np.add(A, B, out=A)

np.divide(-A, 2, out=A)

np.negative(A, out=A)

np.multiply(A, A, out=A)

print(A)

[ 9. 16. 25. 36.]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [11]:
A = np.random.uniform(1,10,10)
print(A)

#첫번째 방법
print(A - A%1)

#두번째 방법
print(A // 1)


[7.62200476 5.71310494 6.87896642 6.32014706 8.04812137 8.64404906
 3.61970054 4.42176227 3.47471195 6.03942457]
[7. 5. 6. 6. 8. 8. 3. 4. 3. 6.]
[7. 5. 6. 6. 8. 8. 3. 4. 3. 6.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [12]:
row_value = np.tile(np.arange(5), (5, 1))
print(row_value)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [13]:
A = np.random.random(10)
sorted_A = np.sort(A)

print(A)
print(sorted_A)


[0.11949261 0.71408822 0.47004539 0.90483746 0.92627628 0.46909659
 0.84613948 0.76078729 0.38660412 0.12636967]
[0.11949261 0.12636967 0.38660412 0.46909659 0.47004539 0.71408822
 0.76078729 0.84613948 0.90483746 0.92627628]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [14]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)

np.array_equal(A,B)

[0 1 0 0 0]
[0 1 0 1 1]


False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [16]:
cartesian = np.random.rand(10, 2) * 10
print("cartesian coodinate:\n", cartesian)

x = cartesian[:, 0] #x좌표
y = cartesian[:, 1] #y좌표

r = np.sqrt(x**2 + y**2) #반지름r = sqrt(x^2 + y^2) 식 이용
theta = np.arctan2(y, x) #각도 계산

polar_coordinates = np.column_stack((r, theta))
print("\npolar coordinate (r, θ):\n", polar_coordinates)

cartesian coodinate:
 [[4.24705775 9.75535487]
 [5.24322009 2.427061  ]
 [5.73534052 9.80365627]
 [9.25956798 8.56934461]
 [8.15141055 6.0822333 ]
 [4.64797162 5.14335262]
 [1.70645059 1.7266017 ]
 [0.84263297 9.96720535]
 [9.12098092 5.9767934 ]
 [7.90287501 1.8284784 ]]

polar coordinate (r, θ):
 [[10.6397579   1.16018638]
 [ 5.77771426  0.43352562]
 [11.35807233  1.04146394]
 [12.61638879  0.74670378]
 [10.17049929  0.64103715]
 [ 6.9323673   0.83594893]
 [ 2.42757637  0.79126783]
 [10.00276025  1.48645633]
 [10.90478576  0.58007782]
 [ 8.11164389  0.22736799]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [17]:
Z = np.random.random(10)
print(Z)

Z[Z.argmax()] = 0
print(Z)

[0.78068828 0.25994497 0.0666702  0.02573083 0.97109682 0.4789254
 0.49226244 0.29416222 0.7504321  0.94699044]
[0.78068828 0.25994497 0.0666702  0.02573083 0.         0.4789254
 0.49226244 0.29416222 0.7504321  0.94699044]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [18]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z)
print(v)

distances = np.abs(Z - v)
closest_index = np.argmin(distances)
closest_value = Z[closest_index]

print(closest_value)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
66.85810368713699
67


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [19]:
import numpy as np
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [20]:
n = 5
p = 8
Z = np.zeros((n, n))

indices = np.random.choice(range(n * n), p, replace=False)
np.put(Z, indices, 1)

print(Z)

[[1. 0. 1. 0. 0.]
 [0. 1. 1. 0. 1.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [21]:
Z = np.random.randint(0,10,(3,3))
print("원래 배열:\n", Z)

원래 배열:
 [[0 7 6]
 [3 3 5]
 [7 0 4]]


In [22]:
# column 1
n = 1
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

1번째 열을 기준으로 정렬된 배열:
 [[0 7 6]
 [3 3 5]
 [7 0 4]]


In [23]:
# column 2
n = 2
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

2번째 열을 기준으로 정렬된 배열:
 [[7 0 4]
 [3 3 5]
 [0 7 6]]


In [24]:
# column 3
n = 3
sorted_Z = Z[Z[:, n-1].argsort()]
print(f"{n}번째 열을 기준으로 정렬된 배열:\n", sorted_Z)

3번째 열을 기준으로 정렬된 배열:
 [[7 0 4]
 [3 3 5]
 [0 7 6]]
