<a href="https://colab.research.google.com/github/hamiin47/Assignment/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
size_of_null_vector = null_vector.nbytes
print(size_of_null_vector)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
vector1 = np.arange(start=10, stop=50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
vector2 = np.sort(vector1)[::-1]
print(vector2)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
array1 = np.arange(9)
array2 = array1.reshape(3,3)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [26]:
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)[0]
print(indices)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [14]:
matrix10 = np.identity(3)
print(matrix10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [16]:
matrix11 = np.random.random((3,3,3))
print(matrix11)

[[[0.10626329 0.22212145 0.82631523]
  [0.17195164 0.82552257 0.21752499]
  [0.3392132  0.77155307 0.38456517]]

 [[0.66537004 0.03484403 0.162086  ]
  [0.96696308 0.29353014 0.93859744]
  [0.96512366 0.73039685 0.80086684]]

 [[0.31030878 0.46075838 0.76683303]
  [0.59589212 0.83481684 0.25092562]
  [0.43380742 0.39426214 0.01496858]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [17]:
matrix12 = np.random.random((10, 10))
print(matrix12)
print('min :', np.min(matrix12), 'max:',np.max(matrix12))

[[0.90273397 0.55766465 0.80334435 0.63068572 0.80074993 0.06884851
  0.40015327 0.94638665 0.25220974 0.03316916]
 [0.04575036 0.71623831 0.38165593 0.2006023  0.91893468 0.49657724
  0.68178878 0.56556883 0.16608998 0.36173458]
 [0.60129946 0.59351026 0.33552983 0.99160281 0.64830107 0.59504463
  0.60369546 0.65720862 0.95474343 0.4422705 ]
 [0.87340808 0.65628611 0.69440478 0.54578258 0.57964087 0.63009958
  0.8351088  0.97268157 0.45571502 0.79939047]
 [0.07171983 0.22034619 0.65412555 0.24211289 0.10795985 0.60427645
  0.33199503 0.75750665 0.79515175 0.74812428]
 [0.99794652 0.64572579 0.71173046 0.8124547  0.48321633 0.07316943
  0.41849609 0.00759352 0.52361045 0.47269212]
 [0.21109067 0.86731469 0.23922299 0.070103   0.18920586 0.09193648
  0.16963791 0.10216728 0.70928507 0.0446544 ]
 [0.44889318 0.5481978  0.05807119 0.7834959  0.67651676 0.57166642
  0.42753746 0.44361006 0.84534183 0.43821266]
 [0.11084583 0.54017711 0.82572614 0.75694652 0.75978365 0.96846299
  0.8063858 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [27]:
matrix13 = np.random.random(30)
print(matrix13)
print('mean:',np.mean(matrix13))

[0.81099836 0.55945254 0.09194156 0.96967165 0.73383049 0.50389035
 0.06497885 0.41189976 0.30795815 0.87245813 0.65673549 0.14968572
 0.07908414 0.95867018 0.29242807 0.86680299 0.26044355 0.67240075
 0.93419102 0.0539306  0.91934363 0.74074809 0.80779922 0.68924839
 0.58601738 0.58217952 0.47330124 0.9213402  0.10849069 0.18478783]
mean: 0.5421569511281558


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
matrix14 = np.ones((4,4))
matrix14[1:-1, 1:-1] = 0
print(matrix14)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, False, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [20]:
matrix16 = np.zeros((5,5))
matrix16[1, 0] = 1
matrix16[2, 1] = 2
matrix16[3, 2] = 3
matrix16[4, 3] = 4
print(matrix16)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
matrix17 = np.zeros((8,8))
matrix17[1::2, ::2] = 1
matrix17[::2, 1::2] = 1
print(matrix17)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [22]:
np.unravel_index(100, shape=(6,7,8))

(1, 5, 4)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [28]:
matrix19 = np.random.random((5,5))
x_bar = np.mean(matrix19)
std = np.std(matrix19)
matrix19 = (matrix19 - x_bar) / std
print(matrix19)

[[-1.51563273 -0.88325969 -1.18150244  1.19579389  0.18157062]
 [-0.20411459  0.7228496  -0.11084442 -0.10187249 -0.66994634]
 [-0.89232157 -1.13539706  1.4112323   1.13791241  1.27459068]
 [-0.17651948  1.06996083  1.66218842  1.62595074 -0.50767199]
 [-0.16255218 -1.56994694 -1.20155334 -0.34234987  0.37343565]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [29]:
RGBA_dtype = np.dtype([('Red', np.ubyte), ('Green', np.ubyte), ('Blue', np.ubyte), ('Alpha', np.ubyte)])
print(RGBA_dtype)

[('Red', 'u1'), ('Green', 'u1'), ('Blue', 'u1'), ('Alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3